name: "reMarkable GitHub Tools"
description: "Restore Czech diacritics and translate Markdown files"

inputs:
  run_diacritics:
    description: "Run Czech diacritics restoration"
    required: false
    default: "true"

  run_translate:
    description: "Run Markdown translation"
    required: false
    default: "false"

  diacritics_api:
    description: "Diacritics API URL"
    required: false
    default: "http://lindat.mff.cuni.cz/services/korektor/api/correct"

  diacritics_model:
    description: "Diacritics model"
    required: false
    default: "czech-diacritics_generator"


runs:
  using: "composite"
  steps:

    - name: Install Python dependencies
      shell: bash
      run: |
        pip install requests transformers sentencepiece torch sacremoses

    - name: Restore Czech diacritics
      if: inputs.run_diacritics == 'true'
      shell: bash
      env:
        DIACRITICS_API: ${{ inputs.diacritics_api }}
        DIACRITICS_MODEL: ${{ inputs.diacritics_model }}
      run: |
        python ${{ github.action_path }}/.tools/diacritics.py

    - name: Translate Markdown
      if: inputs.run_translate == 'true'
      shell: bash
      run: |
        python ${{ github.action_path }}/.tools/translate.py