name: Restore text and translate Markdown documentation

on:
  workflow_call:

env:
  # ===============================================================================
  # CONFIG DATA
  #
  # PROTECTED_WORDS: Words that should never be changed by translation/correction.
  # ===============================================================================
  DIACRITICS_API: http://lindat.mff.cuni.cz/services/korektor/api/correct
  DIACRITICS_MODEL: czech-diacritics_generator

  # Downloading is only needed because this is a shared workflow called from external repos.
  # Running standalone in this repo would only need: .tools/diacritics.py and .tools/translate.py, no PATH_TOOLS
  PATH_TOOLS: /tmp/tools
  PATH_DIACRITICS: /tmp/tools/.tools/diacritics.py
  PATH_TRANSLATE: /tmp/tools/.tools/translate.py

  PROTECTED_WORDS: "Xovi,Qt,QML,reMarkable"

  # =================================================================
  # CONFIG DIACRITICS (editable)
  #
  # IS_ENABLED_DIACRITICS: only for cs
  # COMMIT_MESSAGE: empty or message
  # DIACRITICS_FILE: empty = all Markdown files or (choose *md file)
  # =================================================================
  IS_ENABLED_DIACRITICS: true
  IS_ENABLED_TRANSLATE: true

  DIACRITICS_FILE: ""
  COMMIT_MESSAGE: "Updated documentation translations"
  
  # ===============================================================
  # CONFIG TRANSLATION (editable)
  #
  # 1. For users whose main language is not English:
  #    - Set your language as the source.
  #    - English README.md will be generated automatically.
  #
  # PATH_SOURCE: .language/cs
  # PATH_SOURCE_LANGUAGE: cs
  
  # PATH_OUTPUT_MAIN: .
  # PATH_OUTPUT_MAIN_LANGUAGE: en
  
  # PATHE_OUTPUT_OTHER: .language
  # PATHE_OUTPUT_OTHER_LANGUAGE: "de, fr, it"
  #
  # ===============================================================
  # ===============================================================
  #
  # 2. For users whose main language is English:
  #    - Use README.md as the source file.
  #    - Only translations into other languages will be generated.
  #
  # PATH_SOURCE: .
  # PATH_SOURCE_LANGUAGE: en
  
  # PATH_OUTPUT_MAIN: ""
  # PATH_OUTPUT_MAIN_LANGUAGE: ""
  
  # PATHE_OUTPUT_OTHER: .language
  # PATHE_OUTPUT_OTHER_LANGUAGE: "cs, de, fr, it"
  # ===============================================================

  # PATH_SOURCE: .
  # PATH_SOURCE_LANGUAGE: en
  
  # PATH_OUTPUT_MAIN: ""
  # PATH_OUTPUT_MAIN_LANGUAGE: ""
  
  # PATHE_OUTPUT_OTHER: .language
  # PATHE_OUTPUT_OTHER_LANGUAGE: "cs, de, fr, it"





  # ===============================================================
  # CONFIG TRANSLATION (editable)
  #
  # SOURCE_LANGUAGE:
  #   Language of the original Markdown files.
  #
  # If SOURCE_LANGUAGE is "en":
  #   Source files are read from repository root.
  #   Other languages are stored in .language/<language>/
  #
  # If SOURCE_LANGUAGE is not "en":
  #   Source files are read from .language/<language>/.
  #   English translation is stored in repository root.
  #
  # TRANSLATE_LANGUAGES:
  #   Languages that should be generated.
  #
  # LANGUAGE_DIRECTORY:
  #   Directory for translated languages.
  #
  # ===============================================================

  SOURCE_LANGUAGE: en

  TRANSLATE_LANGUAGES: "cs, de, fr, it"

  LANGUAGE_DIRECTORY: .language


permissions:
  contents: write

jobs:
  main:
    name: 'Restore text and translate Markdown documentation'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Downloading is only needed because this is a shared workflow called from external repos.
      - name: Checkout tools
        run: |
          git clone --depth 1 https://github.com/PepikVaio/reMarkable_Github_Actions.git ${{ env.PATH_TOOLS }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests
          if [ "${{ env.IS_ENABLED_TRANSLATE }}" = "true" ]; then
            pip install transformers sentencepiece torch sacremoses
          fi

      - name: Add diacritics
        # if: env.IS_ENABLED_DIACRITICS == 'true' && env.PATH_SOURCE_LANGUAGE == 'cs'
        if: env.IS_ENABLED_DIACRITICS == 'true' && env.SOURCE_LANGUAGE == 'cs'
        run: |
          python ${{ env.PATH_DIACRITICS }}

      - name: Translate Markdown files
        if: env.IS_ENABLED_TRANSLATE == 'true'
        run: |
          python ${{ env.PATH_TRANSLATE }}

      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "${{ env.COMMIT_MESSAGE }} [skip ci]"
          git push
